version: "3"

services:
  web:
    image: nginx:alpine
    user: root
    ports:
      - 8080:80
    volumes:
      - ./:/srv
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www


  phpfpm:
    user: root
    image: php:fpm-alpine
    volumes:
      - ./:/srv
    networks:
      - www

networks:
  www: